[google]
spreadsheet_id = "1THmwStR6p0_SUyLEV6-edT0kigANvTCPOkAzN7NaEQE"

[google.service_account]
type = "service_account"
project_id = "gen-lang-client-0058506741"
private_key_id = "f724f4110dba888fa4b69250bbbb51a402aef8c1"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDm9LWedbhIZjit
GM+CqzkDVkUJjUT3yf9wDk0WeaGosT5Pf+fRae9DcAzy9JoMHCmmnw/O/WYUS++7
zmuVPs2849tXRJaHel5NRKVsz79loRDqLUY8GLDEqu1Cu8uPVHC6eV7M9prRWHps
HUC1e6wb8PM9bthMpn3zdgO6nMM0GzDF4Df4ldl7JI8/MCKdlazC3GbYEposjXgc
Qq3S3uiSFP8l0Ce/R0+ciOrS8d7BS+7oFJBW8gUD+oF1doMCCHstX70jYyZInTav
CILgTyR7xcg/eNJuWJXln+6Cj22z8V0iNxdqIVRbMygZC5ENTxLHcGVFZgQ/IUE9
BhZSlRknAgMBAAECggEABg3oLO09FXjIh5Ec73n5lqLOUH/JjQ1YiuF1F9+8YyWy
Uncx5oV2Zjgrvrq2xxZ96QZGbdCqumF7OVsh6tmonwkCGPmNUKPekPv5si6H/+wG
+3yQWMb061LnwVYW8fzur5S67XiRemdtXiQuLBO/4UOhvLyJIwlCR/2R/3RYkacQ
D1dDop6yMnDDUUGZSX7S2BlNwhwiDoDBQPXKgGp8kVEwYxVgi68VmipBXG/0dFUZ
kLPjfQDfk3Hmf3xH12sI+2i/vGalGsGo3ncBZyjx6wZLotbhOMz4ttVd7KL5B/BX
BzhsSvss2arde9dLN6KmyKHrJdpPyIQiHkijhCijUQKBgQD+WAwEZXy+IMjZ4CZl
YfjmGfKwVyFdrZgeO8xgfsUcU+Oot1u6uovbBoMBRNBZEMOhYl6ekYEu+vjhFkE9
7RD5rnqRPQpnyAvbGKgMv7Ml4kyiGUnaAKyggMxXGLOgbuvk+FbM3FY0h7VUZKTz
UMee0Zt/woH0+m81lkYxEyaBUwKBgQDoda2cfsiE+yWBNvd6nHPlhDv87ItJz+Yw
MkMfZwbgPVW9gZAycsHR+no2CxqI7MyQmz/mUEO/otz6dztUn7bGkgI095M63bwH
0zEYhi7CGxSeFR6R9PHEjCc48Lp5F4SUioRGeGpK6eKvPawyAy379utH5Gybg0rV
8gk9C42qXQKBgBm1DIHlQBZ3edWLslXM8TtQpBbut5CgWx+zK5UVOxcB46DJ55uX
/0rD/bnDGsvlxeAp8SZVzpjRBRa7CR0ZOP4DhJ/pa4PR1GDwvQuM1K6fkN9RbwV5
y/jtC7pB5OXyUCV0dFGAc7YbgVhmU8XEBGkpBm6DWl9IcLUZ2z5akSnBAoGAc1EF
We/vC0EHXu1koXeBaudJVvQFOQ2gVGJqt+ZFG/JxWTwvy0bwbXkDLVIezLQj2syZ
S2if4y4ozztcvGMqqaD+5UW3zOj4gS08Wr0d7v6+IJm7e452bRlVz8JjzvRiuclp
SwgrOpSB9orypDC9nBPmrdhcJF1iP3X9LUJQ+aUCgYBKJkwuGFp5weDQjVwhRoUg
OoM/6Kw0tK+KIAwpuhtC1G1QcVjC/nZKNMvTHpcU9TU5xh0HUb5m1QuX10przykY
DiLyWvoycPS16JUCVqtP4UtgJMxZL7AYDnX7NLoimFBVJMsTf/dpkJ7kZtyvqCC9
wCZL8mc4bhfWh+8EyaePSQ==
-----END PRIVATE KEY-----"""
client_email = "dailysnippets@gen-lang-client-0058506741.iam.gserviceaccount.com"
client_id = "102416853588007677179"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dailysnippets%40gen-lang-client-0058506741.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[gemini]
api_key = "AIzaSyBsgpa8OUAfrojJ3KF9B53fZwK432l-27o"

